### PR TITLE
allow app to start on windows - correctly quote file source names - use zero data in default source

### PR DESCRIPTION
**Pull request by LouDou**
Something about the 'random' file on Windows doens't work and causes an exception because the device string ends up malformed.

NUL is a valid (virtual) file on Windows which returns \0's and allows the app to start with the default device options before the user has selected a real input device.

### CODE REVIEW

**Comment by LouDou** [comment]
For reference as well, here's how I made the build on Windows:

```
REM Step 1: install vcpkg and cmake
REM Step 2: use vcpkg to install: boost, qt5, mpir
REM Step 3: install Pothos SDR distribution: https://downloads.myriadrf.org/builds/PothosSDR/
REM Step 4: install python 3.9 (or version matching GNU Radio in the Pothos SDR installation)

set CMAKE="C:\Program Files\CMake\bin\cmake.exe"
set VCPKG_DIR=C:\DATA\SDKs\vcpkg
set POTHOSSDR_DIR=C:\DATA\Apps\PothosSDR
set PYTHON_DIR=C:\Python39

REM Step 5: Run cmake

md build-gqrx
cd build-gqrx

%CMAKE% ^
 -DCMAKE_TOOLCHAIN_FILE:PATH=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake ^
 -DVolk_DIR=%POTHOSSDR_DIR%\lib\cmake\volk ^
 -DPython_ROOT_DIR=%PYTHON_DIR% ^
 -DBUILD_STATIC=ON ^
 -DBUILD_EXAMPLES=OFF ^
 ^
 ../gqrx

REM Step 6: Open solution in VS

start grqx.sln

REM Step 7: Build the solution in VS!
REM Step 8: Find the binaries in src/[Debug|Release]/
```

**Comment by vladisslav2011** [comment]
Using /dev/urandom as an input file on *NIX is a very bad idea. Interpreting /dev/urandom as floats would give +inf, -inf, NaN's and very large correct numbers, but all of these are not correct sample values. These incorrect samples may result in, at least, iir filters runaway or may crash some blocks into exception. May it be better to choose /dev/zero, that outputs safe zeroes?

**Comment by LouDou** [comment]
I agree it seems like asking for trouble. I've changed it and the function name.

**Comment by argilo** [comment]
> Something about the 'random' file on Windows doens't work

The existing code already has a fallback for non-Unix systems. I'd like to understand why it's not working before making changes.

**Comment by LouDou** [comment]
> The existing code already has a fallback for non-Unix systems. 

I don't see it; it's been called in the receiver constructor unconditionally and using /dev/<something> even on windows.

**Comment by argilo** [comment]
The `if (!checkFile.exists())` block is meant to handle non-Unix operating systems.

**Comment by argilo** [comment]
Also, the `get_random_file` function was originally created to support Windows: (#332, #335), and I've used Gqrx on Windows (installed through Conda) and didn't have a problem. So the problem you're seeing doesn't affect all Windows installations, and I'd like to know why that is before making changes.

**Comment by LouDou** [comment]
Right. So for whatever reason, that branch wasn't taken on the Windows build. It also intends to create a temp file with random data, which would potentially cause the same issues as reading from /dev/urandom.

I'll run my build through the debugger and find out what's happening.

I have seen the same error behaviour in the gqrx binary shipped in the Pothos SDR bundle.

**Comment by argilo** [comment]
Another point to consider is that we can probably just get rid of the ugly hack of reading from a random (or null) file. I did some of the work in #750.

I think a good path forward would be to use a Null Source block in place of the Osmosdr Source block. This will be necessary if we replace gr-osmosdr with gr-soapy, which is something I'd like to do anyway.

**Comment by argilo** [comment]
> a good path forward would be to use a Null Source block

Or perhaps we could just leave the flow graph disconnected when no device is selected.

In either case, adjustments would need to be made, since the current code assumes that an Osmocom Source block is always present.

**Comment by LouDou** [comment]
I found the problem with the original implementation. The temp file is created but the final path has a space in it:

```
std::string teststr = "file=C:/Users/My Name/AppData/Local/Temp/gqrx.nERGgV,freq=428e6,rate=96000,repeat=true,throttle=true";
```

Which does not parse in the osmocom source node. Incidentally, escaping the space spaces works.

```
std::string teststr = "file=C:/Users/My\\ Name/AppData/Local/Temp/gqrx.nERGgV,freq=428e6,rate=96000,repeat=true,throttle=true";
```

----

But, given that gqrx doesn't even need to read this file at all (it has no meaningful data in it), accepting the patch for `NUL` might be a quick fix until someone can do the additional work of not requiring the default source at all.

**Comment by argilo** [comment]
> Which does not parse in the osmocom source node. Incidentally, escaping the space works.

Aha! I'm glad you were able to track down the root cause.

> accepting the patch for NUL might be a quick fix

I'd hesitate to do this for two reasons:

* It adds another `#ifdef` to the codebase. I've been trying to get rid of those, since conditionally compiled code makes debugging and testing more difficult.
* It doesn't address the underlying bug.

I'd rather fix the escaping bug. In addition to the two places that use `get_random_file`, it looks like the same bug is present here:

https://github.com/gqrx-sdr/gqrx/blob/75d108f7e9b0bb69bb1847173d957b8e41a0cc8f/src/applications/gqrx/mainwindow.cpp#L1602-L1603

**Comment by argilo** [comment]
Actually I see there are quotes around the filename in that third case, so spaces and commas probably work fine. (But I guess there would still be breakage if the filename contained `'` or `\`.)

We could put quotes around the filename on these two lines to make spaces (and commas) work properly:

https://github.com/gqrx-sdr/gqrx/blob/75d108f7e9b0bb69bb1847173d957b8e41a0cc8f/src/applications/gqrx/receiver.cpp#L79

https://github.com/gqrx-sdr/gqrx/blob/75d108f7e9b0bb69bb1847173d957b8e41a0cc8f/src/applications/gqrx/receiver.cpp#L218

**Comment by argilo** [comment]
On the gr-osmosdr side, parsing is done with `boost::escaped_list_separator`:

https://github.com/osmocom/gr-osmosdr/blob/a100eb024c0210b95e4738b6efd836d48225bd03/lib/arg_helpers.h#L66

Its escaping rules are documented here: https://www.boost.org/doc/libs/1_31_0/libs/tokenizer/escaped_list_separator.htm

**Comment by argilo** [comment]
Does this patch fix the Windows startup issue?
```diff
diff --git a/src/applications/gqrx/receiver.cpp b/src/applications/gqrx/receiver.cpp
index fd6e44a0ec..e140428875 100644
--- a/src/applications/gqrx/receiver.cpp
+++ b/src/applications/gqrx/receiver.cpp
@@ -76,7 +76,7 @@ receiver::receiver(const std::string input_device,
 
     if (input_device.empty())
     {
-        src = osmosdr::source::make("file="+get_random_file()+",freq=428e6,rate=96000,repeat=true,throttle=true");
+        src = osmosdr::source::make("file='"+get_random_file()+"',freq=428e6,rate=96000,repeat=true,throttle=true");
     }
     else
     {
@@ -215,7 +215,7 @@ void receiver::set_input_device(const std::string device)
     catch (std::exception &x)
     {
         error = x.what();
-        src = osmosdr::source::make("file="+get_random_file()+",freq=428e6,rate=96000,repeat=true,throttle=true");
+        src = osmosdr::source::make("file='"+get_random_file()+"',freq=428e6,rate=96000,repeat=true,throttle=true");
     }
 
     if(src->get_sample_rate() != 0)
```

**Comment by vladisslav2011** [comment]
I don't think that this patch would fix the startup problem in all cases.
I suggest using boost::io:quoted from boost/io/detail/quoted_manip.hpp to escape the file name.

**Comment by LouDou** [comment]
Just tried a few test cases with boost quoted:
```
      std::stringstream ss;
      ss << boost::io::quoted(path, '\\', '\'');
      path =  ss.str();
```
Using a single quote `'` because double quote `"` does not work at all.


and consuming it like
```
        std::string srcstr = "file=" + get_zero_file() + ",freq=428e6,rate=96000,repeat=true,throttle=true";
        src = osmosdr::source::make(srcstr);
```


Forming these device strings:

1. If the file path has spaces:
```
file='/tmp/test space/\'foo.ENBmWW',freq=428e6,rate=96000,repeat=true,throttle=true
```
This works.


2. If the file path also contains the quote character:
```
file='/tmp/test space/\'foo.ENBmWW',freq=428e6,rate=96000,repeat=true,throttle=true
```
It doesn't work.

**Comment by vladisslav2011** [comment]
It works. You have to escape the file name twice:
```
#include <iostream>
#include <sstream>
#include <boost/io/detail/quoted_manip.hpp>


int main()
{
    auto fn="gqrx',t 123#\\.raw";
    std::stringstream ss1;
    std::stringstream ss2;
    std::string res;
    ss1<<boost::io::quoted(fn,'\\','\'');
    ss2<<boost::io::quoted(ss1.str(),'\\',',');
    res=ss2.str();
    if(res[0]==',')
        res=res.substr(1,res.size()-2);
    std::cout<<"file="<<res<<std::endl;

    return 0;
}
```
result:
```
file='gqrx\\'\,t 123#\\\\.raw'
```

**Comment by LouDou** [comment]
I've pushed a change which uses this quoting strategy wherever a "file=" device string is used.

It'll need some testing on other Windows boxes; I've got inconsistent build behaviour here:
- Debug build - cannot start, crashes trying to create the top-block, therefore doesn't even get to this code
- RelWithDebInfo - produces empty strings for the temp_file name, therefore the "file=" string becomes malformed
- Release - seems to work, but as I cannot attach the debugger nor see any console output, I cannot see the exact string it created and used

🤷

**Comment by vladisslav2011** [comment]
>Release - seems to work, but as I cannot attach the debugger nor see any console output

I have no windows machine to test, but maybe this would help with console output:

src/CMakelists.txt
```
#build a win32 app, not a console app
if (WIN32)
    set(CMAKE_EXE_LINKER_FLAGS "/entry:mainCRTStartup ${CMAKE_EXE_LINKER_FLAGS}")
    set_target_properties(${PROJECT_NAME} PROPERTIES WIN32_EXECUTABLE ON)
endif (WIN32)
```
Remove this "if" block and gqrx should become windows console application (I guess).

**Comment by argilo** [comment]
> You have to escape the file name twice

I had a look under the hood in gr-osmosdr and the outer escaping layer actually uses space as the separator instead of comma. And I guess technically that layer of escaping should be done on the whole argument list rather than just the filename.

Also, we can use `std::quoted` and avoid another dependence on Boost if we update Grqx to use C++14. (I don't see a reason not to do that.)

**Comment by argilo** [comment]
Actually I don't think the difference in delimiter matters, since `std::quoted` always quotes the string.

The following escaping code should work properly:
```cpp
#include <iostream>
#include <iomanip>
#include <sstream>

int main()
{
    std::string fn = "a b\\c'd.raw";
    std::stringstream ss1;
    std::stringstream ss2;
    std::string res;

    ss1 << std::quoted(fn, '\'', '\\');
    ss2 << std::quoted(ss1.str(), '\'', '\\');
    res = ss2.str();

    std::cout << res << std::endl;
}
```

**Comment by argilo** [comment]
I did a bit of cleanup and put these changes into #1012. Please let me know what you think.

**Comment by argilo** [comment]
Closing, since this was fixed in #1012.

**Pull request closed without merging**
