### PR TITLE
Rename appdata file to metainfo

### PR DESCRIPTION
**Pull request by AsciiWolf**
Not a big deal, but the metainfo.xml suffix is preferred nowadays. See the [official AppStream documentation](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location).

### CODE REVIEW

**Comment by AsciiWolf** [comment]
The macOS CI fail is unrelated.

**Comment by AsciiWolf** [comment]
@argilo Feel free to ask if you have any questions. :-)

**Comment by argilo** [comment]
I have considered this, but I didn't make the change because it would require many distribution maintainers to update their packaging. Do you think it's worth it?

**Comment by AsciiWolf** [comment]
That's a very good point and you are probably right. We already install the file in a non-deprecated location and the `.metainfo.xml` suffix is more of a cosmetic thing since most AppStream parsers do not care much about the file suffix if it gets installed in a correct location. Thanks for your comment, I am closing this PR. :-)

**Comment by argilo** [comment]
It may still be worth slipping this in the next time there is a major change that requires packaging updates anyway (perhaps the same time as a switch from gr-osmosdr to gr-soapy, if and when that happens).

**Pull request closed without merging**
